### ISSUE TITLE
New OnUpdate is a breaking change

### ISSUE THREAD

**Issue by costela** [Unleash/unleash-client-go#198]
### Describe the bug

The new `OnUpdate` method added to the `RepositoryListener` interface in #196 was released as 4.5.0, but it's actually a breaking change: existing implementations of `RepositoryListener` now get silently ignored (since the existing code does not match the new larger interface). Code compiles and runs, but doesn't do what it should.

The change should probably have been released as v5?

This is related to the old issue reported in https://github.com/Unleash/unleash-client-go/issues/113, which kinda went under the radar 🫤 

### Logs, error output, etc.

```bash

```

### Subscription type

None

### Hosting type

None

**Comment by gastonfournier** [comment]
Hi @costela sorry, for the mistake. You're correct, it should have been a major, which we now released. Please, let me kno if we can close this and also related to the other issue that went under the radar, is it ok to keep it closed?

**Comment by costela** [comment]
Thanks @gastonfournier! This issue can be closed with the release of 5.x, thanks! 🙏 

IMHO this issue is further evidence that https://github.com/Unleash/unleash-go-sdk/issues/113 is a real problem 😅 

If it's ok with you, I'd suggest reopening the other one. I can't promise I'll get the time for a PR, but the issue remains.

**Comment by gastonfournier** [comment]
Thanks @costela I reopened 113
